# Generated by Django 4.2.8 on 2024-01-01 16:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_code", models.CharField(max_length=32, verbose_name="Course Code")),
                ("course_name_en", models.CharField(max_length=128, verbose_name="Course English Name")),
                ("course_name_cn", models.CharField(max_length=128, verbose_name="Course Chinese Name")),
                ("course_units", models.IntegerField(default=3, verbose_name="Course Credit")),
                ("course_prerequisites", models.CharField(verbose_name="Course Prerequisites")),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("MR", "Major Required"),
                            ("ME", "Major Elective"),
                            ("GEC", "General Education Core"),
                            ("GED", "General Education Distribution"),
                            ("WPE", "Whole Person Education Experiential Learning"),
                            ("FE", "Free Elective"),
                            ("BBA", "BBA (Hons) Core"),
                            ("CR", "Concentration Required"),
                        ],
                        default="MR",
                        max_length=10,
                    ),
                ),
                ("course_description", ckeditor.fields.RichTextField()),
                ("is_visible", models.BooleanField(default=True, verbose_name="Visibility of the course")),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note", models.CharField(max_length=500, verbose_name="Course Note")),
                ("update_time", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="courses.course")),
            ],
        ),
    ]
