# Generated by Django 4.2.8 on 2024-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_lecturer_course_course_exclusions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_exclusions",
            field=models.CharField(default="", verbose_name="Course Exclusions"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_prerequisites",
            field=models.CharField(default="", verbose_name="Course Prerequisites"),
        ),
    ]
