# Generated by Django 4.2.8 on 2024-01-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_alter_course_course_exclusions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursenote",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="notes", to="courses.course"
            ),
        ),
    ]
