# Generated by Django 4.2.8 on 2024-01-30 05:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_coursenote_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="faculties",
            field=models.CharField(blank=True, verbose_name="Lecturer Faculties"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_description",
            field=ckeditor.fields.RichTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name_cn",
            field=models.CharField(blank=True, max_length=128, verbose_name="Course Chinese Name"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("NR", "No Record"),
                    ("MR", "Major Required"),
                    ("ME", "Major Elective"),
                    ("GEC", "General Education Core"),
                    ("GED", "General Education Distribution"),
                    ("WPE", "Whole Person Education Experiential Learning"),
                    ("FE", "Free Elective"),
                    ("BBA", "BBA (Hons) Core"),
                    ("CR", "Concentration Required"),
                ],
                default="NR",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lecturer",
            name="url",
            field=models.URLField(blank=True, verbose_name="Lecturer Homepage URL"),
        ),
    ]
