# Generated by Django 4.2.8 on 2024-01-30 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_lecturer_faculties_alter_course_course_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturer",
            name="alternative_name",
            field=models.CharField(blank=True, verbose_name="Alternative Name"),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("semester", models.CharField(verbose_name="Semester")),
                ("summary", models.CharField(verbose_name="Short Review Summary")),
                ("content", models.TextField(blank=True, verbose_name="Content Comment")),
                ("teaching", models.TextField(blank=True, verbose_name="Teaching Comment")),
                ("grading", models.TextField(blank=True, verbose_name="Grading Comment")),
                ("workload", models.TextField(blank=True, verbose_name="Workload Comment")),
                ("mid_term", models.BooleanField(default=False, verbose_name="Has Mid-term")),
                ("final_exam", models.BooleanField(default=True, verbose_name="Has Final Exam")),
                ("quiz", models.BooleanField(default=False, verbose_name="Has Quiz")),
                ("assignment", models.BooleanField(default=False, verbose_name="Has Assignment")),
                ("essay", models.BooleanField(default=False, verbose_name="Has Essay")),
                ("project", models.BooleanField(default=False, verbose_name="Has Project")),
                ("attendance", models.BooleanField(default=False, verbose_name="Has Attendance")),
                ("reading_material", models.BooleanField(default=False, verbose_name="Has Reading Material")),
                ("presentation", models.BooleanField(default=False, verbose_name="Has Presentation")),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturer_reviews",
                        to="courses.lecturer",
                    ),
                ),
            ],
        ),
    ]
