# Generated by Django 4.2.8 on 2024-01-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_lecturer_alternative_name_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="content_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                default="C",
                verbose_name="Content Letter Grade",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="grading_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                default="C",
                verbose_name="Grading Letter Grade",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="teaching_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                default="C",
                verbose_name="Teaching Letter Grade",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="workload_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                default="C",
                verbose_name="Workload Letter Grade",
            ),
        ),
    ]
