# Generated by Django 4.2.8 on 2024-01-30 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_review_content_grade_review_grading_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="courses.course"
            ),
            preserve_default=False,
        ),
    ]
