# Generated by Django 4.2.8 on 2024-01-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_review_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="lecturer",
        ),
        migrations.AddField(
            model_name="review",
            name="lecturer",
            field=models.ManyToManyField(blank=True, to="courses.lecturer", verbose_name="Lecturers"),
        ),
    ]
