# Generated by Django 4.2.8 on 2024-01-30 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_remove_review_lecturer_review_lecturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="course_reviews", to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="semester",
            field=models.CharField(
                choices=[
                    ("NOTSPEC", "Not Specified"),
                    ("23-24-1", "2023-2024 Fall"),
                    ("22-23-4", "2022-2023 Summer"),
                    ("22-23-3", "2022-2023 Spring"),
                    ("22-23-2", "2022-2023 Winter"),
                    ("22-23-1", "2022-2023 Fall"),
                    ("21-22-4", "2021-2022 Summer"),
                    ("21-22-3", "2021-2022 Spring"),
                    ("21-22-2", "2021-2022 Winter"),
                    ("21-22-1", "2021-2022 Fall"),
                    ("20-21-4", "2020-2021 Summer"),
                    ("20-21-3", "2020-2021 Spring"),
                    ("20-21-2", "2020-2021 Winter"),
                    ("20-21-1", "2020-2021 Fall"),
                    ("19-20-4", "2019-2020 Summer"),
                    ("19-20-3", "2019-2020 Spring"),
                    ("19-20-2", "2019-2020 Winter"),
                    ("19-20-1", "2019-2020 Fall"),
                ],
                default="NOTSPEC",
                verbose_name="Semester",
            ),
        ),
    ]
