# Generated by Django 4.2.8 on 2024-01-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_review_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="submit_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
