# Generated by Django 4.2.8 on 2024-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_review_submit_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "course"), name="one_review_per_course_for_an_user"
            ),
        ),
    ]
