# Generated by Django 4.2.8 on 2024-02-04 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0015_alter_course_course_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to="courses.course",
                verbose_name="Review Course",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="lecturer",
            field=models.ManyToManyField(blank=True, to="courses.lecturer", verbose_name="Lecturer"),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Comments will only display the UID or nickname set by the user, and other information (such as email) will not be displayed in the front desk.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="summary",
            field=models.CharField(max_length=100, verbose_name="Short Review Summary"),
        ),
    ]
