# Generated by Django 4.2.8 on 2024-02-04 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0016_alter_review_course_alter_review_lecturer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Comments will only display the UID or nickname set by the user, and other information (such as email) will not be displayed in the front desk.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
    ]
