# Generated by Django 4.2.8 on 2024-02-07 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0017_alter_review_reviewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("NR", "No Record"),
                    ("MR", "Major Required"),
                    ("ME", "Major Elective"),
                    ("GE", "General Education"),
                    ("UC", "University Core"),
                    ("FE", "Free Elective"),
                    ("BBA", "BBA (Hons) Core"),
                    ("CR", "Concentration Required"),
                    ("MX", "Mixed Type (Check Notes For Detail)"),
                ],
                default="NR",
                max_length=10,
                verbose_name="Course Type",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                help_text="Comments will only display the UID or nickname set by the user, and other information (such as email) will not be displayed in the webpage.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewer",
            ),
        ),
    ]
