# Generated by Django 4.2.8 on 2023-12-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=255, verbose_name="Study Department"),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(blank=True, max_length=255, verbose_name="Study Major"),
        ),
    ]
