# Generated by Django 4.2.8 on 2024-01-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_department_user_major"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="input your preferred display name, this name will show under your reviews.",
                max_length=255,
                verbose_name="Name of User",
            ),
        ),
    ]
